baseURL = 'https://www.v01.io/'
title = 'Klaus Breyer - CTPO: Startup Strategy, Product Execution & Tech Leadership'
copyright = 'KLAUS BREYER'
# sectionPagesMenu = 'main'
preserveTaxonomyNames = true
enableRobotsTXT = true

languageCode = 'en'
defaultContentLanguage = 'en'
[languages]
  [languages.de]
  [languages.en]



[author]
  name = 'Klaus Breyer'

[sitemap]
  changefreq = 'monthly'


[social]
  twitter = 'klausbreyer'

[params]
  repo = "https://github.com/klausbreyer/v01.io/blob/main/content/"
  description = "Iâ€™m Klaus Breyer. With a lifetime in tech, a degree in Software Engineering, and a passion for innovation, I went from founding my first startup in 2010 to playing key roles as CTO/CTPO in many others."
  image = 'images/klaus-breyer.jpg'
  title = 'Klaus Breyer - CTPO: Startup Strategy, Product Execution & Tech Leadership'

[privacy]
  [privacy.youtube]
    privacyEnhanced = true


[menu]

[[menu.main]]
  name = 'Home'
  url = '/'
  weight = 5


[[menu.main]]
  name = 'CV'
  url = '/pages/cv/'
  weight = 30


[[menu.main]]
  name = 'Bookshelf'
  url = '/pages/bookshelf/'
  weight = 45

[[menu.main]]
  name = 'Appearances'
  url = '/pages/appearances/'
  weight = 50

[[menu.main]]
  name = 'Blog'
  url = '/posts/'
  weight = 60


# [[menu.main]]
#   name = 'Funding'
#   url = '/pages/funding/'
#   weight = 60

# [[menu.main]]
#   name = 'unixtime.app'
#   url = '/categories/unixtime.app/'
#   weight = 110

# [[menu.main]]
#   identifier = 'qwer'
#   name = 'This is the qwer section'
#   title = 'qwer section'
#   url = '/qwer/'
#   weight = -110
#   parent = "asdf"
